smbc-digital/iag-webapp

src/StockportWebapp/Parsers/IFrameTagParser.cs
src/StockportWebapp/Parsers/IShareTagParser.cs
src/StockportWebapp/Parsers/VideoTagParser.cs
src/StockportWebapp/Views/healthystockport/Shared/CookieBanner.cshtml
src/StockportWebapp/Views/stockportgov/Article/Article.cshtml
src/StockportWebapp/Views/stockportgov/Comms/Index.cshtml
src/StockportWebapp/Views/stockportgov/Shared/Semantic/Showcase/ProfilesList.cshtml
src/StockportWebapp/Views/stockportgov/Shared/TagManager/TagManagerNoScript.cshtml

- Add param to iFrame tag parser to pass through title to element
- {{ IFRAME:{url};{title} }}
- Add param to IShare tag parser to pass through title to element
- {{ ISHARE:{mapSource};{panelOne};{panelTwo};{layers};{title} }}
- Add param to Video tag parser to pass through title to element
- {{ VIDEO:{id};{token};{title} }}
- Change text on cookie banner
- Amend 'More' link on articles to add in Parent topic name
- Add alt text to profile images on showcase

fix: accessibility issues

---

src/StockportWebapp/Parsers/IFrameTagParser.cs
src/StockportWebapp/Parsers/IShareTagParser.cs
src/StockportWebapp/Parsers/VideoTagParser.cs
src/StockportWebapp/Views/healthystockport/Shared/CookieBanner.cshtml
src/StockportWebapp/Views/stockportgov/Article/Article.cshtml
src/StockportWebapp/Views/stockportgov/Comms/Index.cshtml
src/StockportWebapp/Views/stockportgov/Shared/Semantic/Showcase/ProfilesList.cshtml
src/StockportWebapp/Views/stockportgov/Shared/TagManager/TagManagerNoScript.cshtml
test/StockportWebappTests/Unit/Parsers/VideoTagParserTest.cs

Reverts smbc-digital/iag-webapp#17

Revert "fix: accessibility issues"

---

src/StockportWebapp/Controllers/ServicePayPaymentController.cs
src/StockportWebapp/Enums/EPaymentSubmissionType.cs
src/StockportWebapp/Models/PaymentSubmission.cs
src/StockportWebapp/Models/ServicePayPaymentSubmission.cs
src/StockportWebapp/Validation/EmailValidation.cs
src/StockportWebapp/Validation/PaymentReferenceValidation.cs
src/StockportWebapp/ViewModels/ServicePayPaymentSubmission.cs
src/StockportWebapp/Views/stockportgov/ServicePayPayment/Detail.cshtml

Added displayname for validation message on inputs
Added bool to ViewModel for when payment amount has been provided by service
Fixed PaymentReferenceValidation to work with both payment types

fix: service pay payment

---

src/StockportWebapp/wwwroot/assets/sass/stockportgov/modules/_leaflet.scss

Updated map container div height to 700px.

chore(maps): updated map container height

---

src/StockportWebapp/Scheduler/QuartzJob.cs
src/StockportWebapp/Scheduler/QuartzJobFactory.cs
src/StockportWebapp/Scheduler/QuartzScheduler.cs
src/StockportWebapp/Startup.cs
test/StockportWebappTests/Unit/Scheduler/QuartzJobTests.cs

- Added logger to QuartzJob to log updated redirects count
- Removed DI which are not used anymore within QuartzJob

chore(redirects): added log to validate redirects count on update

---

src/StockportWebapp/Scheduler/QuartzScheduler.cs

Updated quartz job to start 5 seconds after app deploy.

chore(Quartz): change scheduler start time

---

src/StockportWebapp/Views/stockportgov/Shared/GenericFeaturedItem.cshtml
src/StockportWebapp/Views/stockportgov/Shared/NewsListing.cshtml

Includes:
- Added no follow to anchor links to preent search engine traffic from following filter links on news and groups

feat(Views): Added no follow to anchor links

---

src/StockportWebapp/Models/CommsHomepage.cs
src/StockportWebapp/Views/stockportgov/Comms/Index.cshtml

Add null check in view if there are no Basic Links

feat(replace_basic_links): add null check in view

---

src/StockportWebapp/Views/Shared/Carousel.cshtml

- Update carousel view to include aria-label and title attribute

chore(views): carousel title & aria-heading

---

src/StockportWebapp/Views/stockportgov/Shared/GenericFeaturedItemList.cshtml
src/StockportWebapp/wwwroot/assets/javascript/stockportgov/EventFeatureItemFocus.js
src/StockportWebapp/wwwroot/assets/javascript/stockportgov/EventFeatureItemFocus.min.js

Fix to the tabbing order on the homepage when the 'View more services' button is selected.

Focus Orders on "View More" behaviours homepage

---

src/StockportWebapp/Parsers/VideoTagParser.cs
test/StockportWebappTests/Unit/Parsers/VideoTagParserTests.cs

Added additional chars to VideoTagParser for title

fix: Added additional chars to VideoTagParser for title

---

src/StockportWebapp/ContentFactory/ShowcaseFactory.cs
src/StockportWebapp/Models/Showcase.cs
src/StockportWebapp/Models/SocialMediaLink.cs
src/StockportWebapp/ProcessedModels/ProcessedShowcase.cs
src/StockportWebapp/Views/Shared/Components/SemanticFooterSocialMediaLinks/Default.cshtml
src/StockportWebapp/Views/Shared/SocialMediaLinks.cshtml
src/StockportWebapp/Views/stockportgov/Shared/Semantic/Showcase/SocialMediaLinks.cshtml
test/StockportWebappTests/Unit/Controllers/ShowcaseControllerTest.cs
test/StockportWebappTests/Unit/TestBuilders/ShowcaseBuilder.cs

-Rename property name from 'Platform' to 'AccountName'
-Fix unit test
-Revert showcase class because platform property not needed

Improve aria label for social media links - update property and bug fix

---

src/StockportWebapp/Views/stockportgov/Shared/GlobalAlert.cshtml

Fixes accessibility issue on "old" non-semantic homepage alerts.

minor: Add title/aria-label non-semantic global alert

---

src/StockportWebapp/Views/stockportgov/Shared/HeaderExternal.cshtml
src/StockportWebapp/Views/stockportgov/Shared/_LayoutExternal.cshtml

- Create new header file called HeaderExternal.
- Update header partial on _LayoutExternal to point to new HeaderExternal file.

(Democracy) Create new header file for LayoutExternal

---

src/StockportWebapp/Views/healthystockport/Shared/SearchResults.cshtml
src/StockportWebapp/Views/stockportgov/Shared/Search.cshtml
src/StockportWebapp/Views/stockportgov/Shared/SearchResults.cshtml

Remove unnecessary 'button' from search button value (StockportGov).
Wrap search results inside div with id 'Content' (StockportGov, HS).

fix(Search): NVDA correctly works on button and main content

---

src/StockportWebapp/Views/stockportgov/Shared/Semantic/EmailBanner.cshtml

chore(emailAlert): add class

---

src/StockportWebapp/Views/healthystockport/Topic/Index.cshtml

Reorder Call To Action to be below Events, not above as stated in the card. Confirmed with Laura yesterday.
also added null check back in for events

fix(CallToAction): moved to below events

---

src/StockportWebapp/Models/EventHomepage.cs
src/StockportWebapp/Views/stockportgov/Events/Index.cshtml
test/StockportWebappTests/Unit/Controllers/EventsControllerTest.cs

Jira Card - Allow Alerts on the events home page (8768)
-) Add Alerts property in EventHomepage and Contentful model
-) Update Event view to display Alerts
Checklist

chore(evethomepage): Add alerts

---

src/StockportWebapp/Controllers/EventsController.cs
src/StockportWebapp/ProcessedModels/ProcessedEvents.cs
src/StockportWebapp/Views/stockportgov/Events/Detail.cshtml

Jira Card - DIGITAL-8769 Add global alerts
-) Add a new property to display global alerts
-) Update View to use new property
Checklist

chore(events):Add global alerts

---

src/StockportWebapp/wwwroot/assets/javascript/stockportgov/viewMoreSlider.js

Part of previous work... just forgot to reinstate the toggle for the button to change the icon ( up / down chevron )

fix(ViewMoreSlider): forgot the button icon toggle

---

src/StockportWebapp/Views/stockportgov/Shared/Semantic/EmailBanner.cshtml

Jira Card - Showcase email sign up bug
-) Style fix for the content and button for different views
Checklist

chore(showcase): fix style for email alert

---

src/StockportWebapp/Controllers/EventsController.cs
src/StockportWebapp/Controllers/GroupsController.cs
src/StockportWebapp/Properties/launchSettings.json
src/StockportWebapp/Views/stockportgov/Events/Index.cshtml
src/StockportWebapp/Views/stockportgov/Groups/ViewGroupsEvents.cshtml
test/StockportWebappTests_Integration/RoutesTest.cs

Jira- Update/Move Add Event form (DIGITAL-8733)
- Update View to redirect to new form.

Update site to use new 'add an event' form

---

src/StockportWebapp/StockportWebapp.csproj
src/StockportWebapp/app-config/appsettings.int.json
src/StockportWebapp/app-config/appsettings.integrationtest.json
src/StockportWebapp/app-config/appsettings.json
src/StockportWebapp/app-config/appsettings.local.json
src/StockportWebapp/app-config/appsettings.prod.json
src/StockportWebapp/app-config/appsettings.qa.json
src/StockportWebapp/app-config/appsettings.stage.json
src/StockportWebapp/app-config/appsettings.uitest.json

Boost logging a bit with some enrichers... changes the output template to reflect the data.
Changed Int to "Debug" to get more information logged.
Changed the deprecated "RollingFile" to "File" for Int.

feat(Logging): Add enrichers to serilog logging

---

src/StockportWebapp/Controllers/GroupsController.cs

fix(groupController): add currentUrl to viewbag

---

src/StockportWebapp/Views/healthystockport/Shared/ContactUs.cshtml
src/StockportWebapp/Views/stockportgov/Shared/ContactUs.cshtml

Looks like a view was missed from the "new" way of loading the assets. Added the right config for ContatUs to Healthy Stockport & Stockport Gov.

fix(ContactUs): require.js update to new assets

---

src/StockportWebapp/StockportWebapp.csproj
src/StockportWebapp/app-config/appsettings.int.json
src/StockportWebapp/app-config/appsettings.json
src/StockportWebapp/app-config/appsettings.local.json
src/StockportWebapp/app-config/appsettings.qa.json

Pretty much just as the commit says

feat(ClientIP): add enricher to log client info

---

src/StockportWebapp/Views/stockportgov/Groups/AddAGroup.cshtml
src/StockportWebapp/Views/stockportgov/Groups/EditEvent.cshtml
src/StockportWebapp/Views/stockportgov/Groups/EditGroup.cshtml

use a class instead to select the textarea

fix(WYSIWYG): use textarea with class

---

src/StockportWebapp/Views/stockportgov/Groups/AddAGroup.cshtml
src/StockportWebapp/Views/stockportgov/Groups/EditEvent.cshtml
src/StockportWebapp/Views/stockportgov/Groups/EditGroup.cshtml

Remove buttons that were not represented... left with the minimum but all working buttons

fix(WYSIWYG): rm buttons that don't work

---

src/StockportWebapp/Controllers/EventsController.cs

The format fix for the 'View more' on Events had caused the same formatting issue on the Events search.
Added a ternary using the FromSearch property to provide the correct formatting for each use case.

chore(controller): add variable for events datetime formatting

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/alert-functionality.cy.js
test/UIAndBrowserTests/cypress/helpers/functions.js

-Added  data-cy="global-alert" to closeAlerts function
-Simplified the closeAlerts function
-Completed the alert-functionality test

Added data-cy="global-alert" to closeAlerts

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/view-more-services-button-functionality.cy.js
test/UIAndBrowserTests/cypress/helpers/functions.js
test/UIAndBrowserTests/package.json

- Add css test for the 'View more services' button.
- Add hexToRgb helper function
- Add dev start function to launch cypress against localhost

View more services button css test

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/view-more-services-button-functionality.cy.js

-Amended the view more services button tests to use a function getMoreServicesButton
-Removed variable  moreServicesButton from test

test(browser): function for view more services button

---

src/StockportWebapp/Views/stockportgov/Shared/HeaderSearchBar.cshtml

Added 'data-cy="show-search" to HeaderSearchBar.cshtml

refactor(Header search) added data-cy to a tag

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/alert-functionality.cy.js
test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/search-functionality.cy.js
test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/view-more-services-button-functionality.cy.js
test/UIAndBrowserTests/cypress/helpers/functions.js

-completed search test 
-added viewport function to functions file
-slight amendments to other tests

test(Webapp browser): completed search test and amended existing tests

---

src/StockportWebapp/Views/stockportgov/Shared/GlobalAlert.cshtml

Added data-cy="alert-icon" to GlobalAlert.cshtml so I can check that the alert icon is hidden on mobile.

refactor(Webapp): added data-cy to global alert icon

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/alert-functionality.cy.js
test/UIAndBrowserTests/cypress/helpers/functions.js

-Moved function from functions file to the alerts test
-Added additional test to cover checking icons are hidden on mobile and not desktop

test(Webapp Browser): added additional test for alerts

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/search-functionality.cy.js
test/UIAndBrowserTests/cypress/helpers/functions.js
test/UIAndBrowserTests/cypress/support/e2e.js
test/UIAndBrowserTests/package-lock.json
test/UIAndBrowserTests/package.json

- Add cy-plugin-tab so we can use the tab key 
- Added another small test to the search functionality file to test tabbing into the search input then tabbing to the search button and pressing the enter key

test(Webapp Browser): added keyboard only test for search

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/alert-functionality.cy.js
test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/search-functionality.cy.js
test/UIAndBrowserTests/cypress/support/commands.js
test/UIAndBrowserTests/cypress/support/e2e.js
test/UIAndBrowserTests/package-lock.json
test/UIAndBrowserTests/package.json

Added additional test to the alerts functionality file to test closing an alert using the enter key.

test(Webapp Browser): added test to dismiss alerts using keyboard

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/navcard-functionality.cy.js

Added an additional test in the navcard-functionality.cy.js file to test navigating using keyboard only.

test(Webapp Browser): navcard test for keyboard navigation

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/alert-functionality.cy.js
test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/navcard-functionality.cy.js
test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/search-functionality.cy.js
test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/top-tasks-functionality.cy.js
test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/view-more-services-button-functionality.cy.js
test/UIAndBrowserTests/cypress/helpers/functions.js
test/UIAndBrowserTests/cypress/helpers/viewports.js

-Created viewports.js and added viewport related functions
-Imported functions in all tests so they use the same viewport sizes

test(Webapp Browser): added viewports function to tests

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/top-tasks-functionality.cy.js

-Added small test to Top Tasks to test keyboard navigation

test(webapp browser): added keyboard only tests for top tasks

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/top-tasks-functionality.cy.js

-Added .should('be.visible','eq','5') to line 21 in top-tasks-functionality.cy.js file.

test(webapp browser): added small change to first test for top tasks

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/condolence-alert-functionality.cy.js

Added condolence alert file with 3 tests.

test(webapp browser): added condolence alert tests

---

src/StockportWebapp/Views/stockportgov/Shared/FeatureCard.cshtml

- Added data-cy="view-more-button"  in FeatureCard.cshtml
- Added data-cy="feature-card-link" in FeatureCard.cshtml

refactor(Webapp): added data-cy id's to Feature card

---

src/StockportWebapp/Views/stockportgov/Shared/GlobalAlert.cshtml

Removed space for data-cy="global-alert-wrapper"

refactor(Webapp): removed random space in data-cy

---

src/StockportWebapp/Views/Shared/Components/Footer2023/Default.cshtml

Added data-cy="footer" to footer for the snapshot tests

refactor(Webapp): added data-cy to footer

---

src/StockportWebapp/Views/Shared/FooterLinks.cshtml

- added data-cy for the footer links

refactor(Webapp): added data-cy for footer links

---

src/StockportWebapp/Views/stockportgov/Shared/EmailSubscribe2023.cshtml

Added data-cy for subscribe button

refactor(Webapp):added data-cy for subscribe button

---

src/StockportWebapp/Views/stockportgov/Shared/FeatureCard.cshtml

Added data-cy for feature card wrapper to feature card html to complete setting up the structure test.

refactor(Webapp):added data cy to feature card

---

src/StockportWebapp/Views/stockportgov/Shared/Search2023.cshtml

* remove role="search" and "aria-label" attributes to improve what is read out by the screen readers

fix(Search2023): fix search form for screen readers

---

src/StockportWebapp/Views/stockportgov/Shared/_Layout2023.cshtml

- remove duplicate DesignSystemjs reference
- converter stylesheets to preload
- update fontawesome to version 6

refactor(layout2023): cleanup layout

---

src/StockportWebapp/ContentFactory/HomepageFactory.cs
src/StockportWebapp/Models/Homepage.cs
src/StockportWebapp/Models/ProcessedModels/ProcessedHomepage.cs
src/StockportWebapp/Views/stockportgov/Home/Index2023.cshtml
src/StockportWebapp/Views/stockportgov/Shared/CallToAction.cshtml
test/StockportWebappTests/Unit/ContentFactory/HomepageFactoryTest.cs
test/StockportWebappTests/Unit/Controllers/HomeControllerTest.cs
test/StockportWebappTests/Unit/Model/ProcessedHomepageTests.cs

Adds the extra CTA option to the homepage

minor: add pimary call to action below top tasks

---

src/StockportWebapp/Controllers/ExternalTemplatesController.cs
src/StockportWebapp/Views/stockportgov/ExternalTemplates/DemocracyExtranet.cshtml

Create an initial new template for the democracy.stockport.gov.uk/modern.gov template for extranet use. url for this will be https://env-url/ExternalTemplates/DemocracyExtranet

Democracy external intranet

---

src/StockportWebapp/Views/stockportgov/Topic/Index2023.cshtml

Section layout is no inside the CTA partial so is no longer needed in the Topic template,

patch: fix the CTA on topic to reflect change in partial

---

src/StockportWebapp/Views/stockportgov/Shared/TopicBreadcrumb.cshtml
src/StockportWebapp/Views/stockportgov/Topic/Index2023.cshtml

Added data-cy for breadcrumbs, h1 and summary

Refactor(Webapp): Added data-cy for breadcrumb,h1 and summary

---

src/StockportWebapp/Views/stockportgov/Shared/TopicSecondaryItems.cshtml

Added data-cy for secondary items.

Refactor(Webapp): data-cy for secondary items

---

src/StockportWebapp/Views/stockportgov/Shared/TopicSecondaryItems.cshtml

Added data-cy to href for secondary items.

Refactor(Webapp):added data cy for secondary item link

---

src/StockportWebapp/Views/stockportgov/Shared/TopicPrimaryItems.cshtml
src/StockportWebapp/Views/stockportgov/Shared/TopicSecondaryItems.cshtml

Added data-cy to section for primary items.

refactor(IAG regression): added data-cy for primary items

---

src/StockportWebapp/Views/stockportgov/Shared/TopicPrimaryItems.cshtml

-added data cy for both image and non image for primary items

added primary items data cy

---

src/StockportWebapp/ContentFactory/TopicFactory.cs
src/StockportWebapp/Models/ProcessedModels/ProcessedTopic.cs
src/StockportWebapp/Models/Topic.cs
src/StockportWebapp/Views/stockportgov/Topic/Index2023.cshtml
test/StockportWebappTests/Unit/Controllers/TopicControllerTest.cs
test/StockportWebappTests/Unit/Model/ProcessedTopicTests.cs
test/StockportWebappTests/Unit/Repositories/TopicRepositoryTests.cs
test/StockportWebappTests/Unit/ViewModels/TopicViewModelTest.cs

Separated out old and new Event Banner within Processed topic

Fix: Event banner model hotfix

---

src/StockportWebapp/Views/stockportgov/Shared/EmailSubscribe2023.cshtml

-Removed icon from subscribe button

removed envelope icon off subscribe button

---

src/StockportWebapp/Views/stockportgov/Groups/AddAGroup.cshtml
src/StockportWebapp/Views/stockportgov/Groups/ChangeGroupInfo.cshtml
src/StockportWebapp/Views/stockportgov/Groups/ChangeGroupInfoConfirmation.cshtml
src/StockportWebapp/Views/stockportgov/Groups/Index.cshtml
src/StockportWebapp/Views/stockportgov/Groups/ReportGroupInfo.cshtml
src/StockportWebapp/Views/stockportgov/Groups/ReportGroupInfoConfirmation.cshtml
src/StockportWebapp/Views/stockportgov/Groups/Results.cshtml
src/StockportWebapp/Views/stockportgov/Groups/ThankYouMessage.cshtml
src/StockportWebapp/Views/stockportgov/Shared/GroupDetail.cshtml

Added data cy id's to cover groups snapshot and structure tests excluding anything to do with managing groups as that is out of scope.

added data cy for groups snapshot tests

---

src/StockportWebapp/Views/stockportgov/Shared/_Layout.cshtml

Test removal of JS from legacy layout page.

patch: remove reference to design system

---

src/StockportWebapp/Views/stockportgov/Article/Article.cshtml
src/StockportWebapp/Views/stockportgov/Comms/Index.cshtml
src/StockportWebapp/Views/stockportgov/Events/Detail.cshtml
src/StockportWebapp/Views/stockportgov/Events/Index.cshtml
src/StockportWebapp/Views/stockportgov/News/Detail.cshtml
src/StockportWebapp/Views/stockportgov/News/Index.cshtml
src/StockportWebapp/Views/stockportgov/Payment/Detail.cshtml
src/StockportWebapp/Views/stockportgov/Profile/index.cshtml
src/StockportWebapp/Views/stockportgov/ServicePayPayment/Detail.cshtml
src/StockportWebapp/Views/stockportgov/Showcase/Showcase.cshtml

added data-cy to pages for regression suite

added data-cy to pages for regression suite

---

src/StockportWebapp/Views/stockportgov/Directory/DirectoryEntry.cshtml
src/StockportWebapp/Views/stockportgov/Directory/Results.cshtml

added data cy for directory entry and search

Refactor: added data cy for directory entry and search

---

src/StockportWebapp/Views/stockportgov/Directory/Results.cshtml

Added data cy to the apply filters button and clear filters link.

refactor(Results):added data cy for apply and clear

---

src/StockportWebapp/Views/stockportgov/Shared/Header.cshtml
src/StockportWebapp/Views/stockportgov/Shared/SemanticHeader.cshtml

Added data cy to 2 headers so I can create 2 extra snapshots.

chore(header):added data cy for old header

---

src/StockportWebapp/Controllers/DirectoryController.cs
src/StockportWebapp/Models/Directory.cs
src/StockportWebapp/Models/DirectoryEntry.cs

fix duplicate entry issue adds comparator for directoryEntry to used with "Distinct" method calls.

patch: fix duplicate entry issue

---

src/StockportWebapp/Controllers/DirectoryController.cs
src/StockportWebapp/Models/DirectoryEntry.cs
src/StockportWebapp/Services/DirectoryService.cs
src/StockportWebapp/ViewModels/DirectoryViewModel.cs
src/StockportWebapp/Views/stockportgov/Directory/Results.cshtml
test/StockportWebappTests/Unit/Controllers/DirectoryControllerTest.cs
test/StockportWebappTests/Unit/Services/DirectoryServiceTests.cs

Commit adds some basic search functionality
You can add ?searchTerm={your-search-term} to the end of directory result URLs.

Search basics

---

src/StockportWebapp/Controllers/DirectoryController.cs
src/StockportWebapp/Views/stockportgov/Shared/DirectoryEntryMap.cshtml

chore(DirectoryEntryMap): update travel mode to driving

---

src/StockportWebapp/Views/stockportgov/Shared/FindOutMoreBanner.cshtml

fix(findOut): button colour on multi enum

---

src/StockportWebapp/Views/stockportgov/Shared/SubscriptionBanner.cshtml

small fix to top margin around subscription banner content block when next to full width image.

patch: fix margin around subscription banner

---

src/StockportWebapp/Views/stockroom/Events/Detail2024.cshtml
src/StockportWebapp/Views/stockroom/Events/Index2024.cshtml
src/StockportWebapp/Views/stockroom/Home/Index.cshtml
test/StockportWebappTests/Unit/Parsers/CallToActionTagParserTests.cs

+ add data-cy attributes for Events/EventsHomepage and Homepage

test(CallToActionTagParserTests): add unit tests

---

src/StockportWebapp/ContentFactory/EventFactory.cs

fix(events): use markdownWrapper on bodyText
