smbc-digital/iag-webapp

src/StockportWebapp/Utils/TypeRoutes.cs

Includes:
- Added case servicePayPayment within routes switch. There currently is a case for "service-pay-payment", this is not the type which is returned from the contentapi but am not sure if it maybe somewhere so have kept the original and added the correct type name to the switch to allow the route to be generated.

chore(Routes): Added Service pay to switch

---

src/StockportWebapp/Controllers/EventsController.cs
src/StockportWebapp/Controllers/GroupsController.cs

Added "Location" property to ResponseCache attribute on some actions within two controllers, which will also set the pragma headers no-cache.
[Jira : Card 6585](https://stockportbi.atlassian.net/browse/DIGITAL-6585)
The reason was in Kibana there was about 5000 logs for this warning over a month, to do with some actions in the Events and Groups controller. According to the [docs](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-5.0#responsecache-attribute) the pragma header will also be set if the Location property is included.
To test : pull the branch and build, make sure no issues... with the endpoints effected.

fix(response_caching): add attribute 'Location'

---

src/StockportWebapp/Models/EventHomepage.cs
src/StockportWebapp/Models/GenericFeaturedItemList.cs
src/StockportWebapp/ProcessedModels/ProcessedGroupHomepage.cs
src/StockportWebapp/ViewModels/GroupStartPage.cs
src/StockportWebapp/Views/stockportgov/Shared/GenericFeaturedItemList.cshtml

-Remove 'View more categories' button from Events and Groups page.
-Display all categories for Events and Groups page.

6572 - Tab orders fix

---

src/StockportWebapp/Views/stockportgov/Comms/Index.cshtml

fix for iframe missing titles on comms page
- Added title attrbiute to 'a' that iframe is attached to for twitter
- Added iframe title to instgram feed
- Added title to facebook feed

fix: move title to div iframe is attached for twitter/instgram

---

src/StockportWebapp/Views/stockportgov/Shared/TertiaryItems.cshtml

Second ul no longer renders if only 1 tertiary item had been provided for topics.

fix(TertiaryItems): add functionality to hide second column if only 1 item exists

---

src/StockportWebapp/Views/stockportgov/Shared/GenericFeaturedItemList.cshtml
src/StockportWebapp/wwwroot/assets/javascript/stockportgov/EventFeatureItemFocus.js
src/StockportWebapp/wwwroot/assets/javascript/stockportgov/EventFeatureItemFocus.min.js
src/StockportWebapp/wwwroot/assets/javascript/stockportgov/viewMoreSlider.js

As per comments in [Jira D-6912](https://stockportbi.atlassian.net/browse/DIGITAL-6912), this fix confirms the focus is to be on the 9th item, which was previously hidden, and the focus-style ( orange border ) is to remain. Also fixes the issue of the current solution, as when you selected "View Less Services" it would try to attach the focus to a hidden element, and that broke in IE & Safari, taking the tab order back to the first item.
-) Removed EventFeatureItemFocus.js and minified version
-) Removed <script> call in GenericFeaturedItemList.cshtml to the above file
-) Added jQuery focus() on 9th featured item, if it is undefined, in viewMoreSlider.js, on the "expand call", ignores it on the "collapse call" within that function.
To test:
Pull the branch. Launch. Visit home page. In all …

fix(tab_order): add focus to 9th item when open

---

src/StockportWebapp/ContentFactory/ShowcaseFactory.cs
src/StockportWebapp/Models/Showcase.cs
src/StockportWebapp/Models/SocialMediaLink.cs
src/StockportWebapp/ProcessedModels/ProcessedShowcase.cs
src/StockportWebapp/Views/Shared/Components/SemanticFooterSocialMediaLinks/Default.cshtml
src/StockportWebapp/Views/Shared/SocialMediaLinks.cshtml
src/StockportWebapp/Views/stockportgov/Shared/Semantic/Showcase/SocialMediaLinks.cshtml

Platform property added to social links in the showcase and footer. This allows us to have 'Platform Title' in the aria label so the screen reader would read out 'Facebook @stockportMBC', whilst maintaining the Title text that's displayed on the page.

feat(socialMediaLinks): add platform property for aria-label

---

src/StockportWebapp/Views/stockportgov/Shared/NewsListing.cshtml

Following from previous [merge](https://github.com/smbc-digital/iag-webapp/commit/5e8607dde3d2cda95b4245c95b175327c61503b5), the 'refined by' heading no longer renders while no active filters exist on the page. 
In addition, the heading tags of both 'Category' and 'News Archive' get bumped to h2 when there are no active filters as to preserve the page heading structure.

News 'refined by' area render when page has no active filters (#6911)

---

src/StockportWebapp/web.config

Changed Web.Config to remove X-Powered-By & Server details from response to request
To test:
Pull the branch. Launch project. Developer Tools > Network > inspect localhost request and see that X-Powered-By and Server details are no longer in the response header

fix(server_headers): rm x-powered-by and server

---

src/StockportWebapp/Views/Shared/Error.cshtml
src/StockportWebapp/Views/healthystockport/Shared/_LayoutError.cshtml
src/StockportWebapp/Views/healthystockport/Shared/_LayoutHome.cshtml
src/StockportWebapp/Views/stockportgov/Shared/_Layout.cshtml
src/StockportWebapp/Views/stockportgov/Shared/_LayoutError.cshtml
src/StockportWebapp/Views/stockportgov/Shared/_LayoutExternal.cshtml
src/StockportWebapp/Views/stockportgov/Shared/_LayoutHome.cshtml
src/StockportWebapp/Views/stockportgov/Shared/_LayoutPrint.cshtml
src/StockportWebapp/Views/stockportgov/Shared/_LayoutSemantic.cshtml

A lot of documentation seems to point towards just sticking with the classic meta viewport settings... I looked back at the original commit for this back in 2017, which added the two other properties, but I don't know why they were added in the first place.

fix(Zoom_Audit); revert to classic meta viewport

---

src/StockportWebapp/Views/healthystockport/Shared/CookieBanner.cshtml
src/StockportWebapp/Views/healthystockport/Shared/Header.cshtml
src/StockportWebapp/Views/stockportgov/Shared/CookieBanner.cshtml
src/StockportWebapp/Views/stockportgov/Shared/Header.cshtml
src/StockportWebapp/Views/stockportgov/Shared/SemanticHeader.cshtml
src/StockportWebapp/Views/stockportgov/StartPage/Index.cshtml

[Jira Issue - tabindex greater than 0](https://stockportbi.atlassian.net/browse/DIGITAL-7235)
Removed tab index from Cookie Banner & Skip Content.... 
**to test**
-) Pull branch.
-) Launch. 
-) Inspect in incognito ( or delete the cookie consent-cookie ), so you can see the cookie consent banner.
You should be able to tab, from page load, to cookie info, then cookie-accept, then skip to main. 
You should be able to run AXE developer tools and see "0" Serious Issues.

fix(tabindex): remove index greater than 0

---

src/StockportWebapp/Views/Shared/Components/Footer/Default.cshtml

Fixed tab ordering on Footer where the first tabbed item was the social media list on far right then it would jump back to the left.
Removed push/pull classes and replaced it with socialmedia links which are only visible on mobile and social media links only visible on tablet/desktop at bottom to keep UX design of socialmedia appearing at the top on mobile view.

fix: Remove push/pull classes for hide-on device classes

---

src/StockportWebapp/Views/healthystockport/Error/Error.cshtml
src/StockportWebapp/Views/stockportgov/Error/Error.cshtml
src/StockportWebapp/wwwroot/assets/javascript/healthystockport/cludo.js
src/StockportWebapp/wwwroot/assets/javascript/stockportgov/cludo.js

[Last PR](https://github.com/smbc-digital/iag-webapp/pull/135) a feature was added that used JQuery DOM update events to check if cludo had returned no results. Chromium browsers had dropped support for that a while ago, so this change swaps that functionality out for [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), which has [full browser](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#browser_compatibility) support. No functional changes have been made.
This PR also includes a small content change to the home page link text.

refactor(404cludo): update dynamic link to work on chromium browsers

---

src/StockportWebapp/Controllers/TopicController.cs
src/StockportWebapp/Models/Topic.cs
src/StockportWebapp/Views/healthystockport/Topic/Index.cshtml
test/StockportWebappTests/Unit/Controllers/TopicControllerTest.cs
test/StockportWebappTests/Unit/ViewModels/ArticleViewModelTest.cs
test/StockportWebappTests/Unit/ViewModels/TopicViewModelTest.cs

Removed logic which added functionality where it was originally mentioned on the card, but after investigation was not actually required at the moment. Confirmed with Jon H & Laura. Issue [Jira #8152](https://stockportbi.atlassian.net/browse/DIGITAL-8152).
To test:
Pull branch and launch.
Check localhost/healthy-stockport-article and you should see a video
Check localhost/topic/uitest-healthy-weight and you should not see a video

fix(video_tag_parser): rm logic for Topic

---

src/StockportWebapp/Views/Shared/Components/Footer/Default.cshtml

Oddity that in our codebase we do not set aria-hidden="true" on any footer element... but it gets set in production environment... so, I suggest we explicitly set this to false to enforce the point and ideally get our accessibility score up to 100. I ran the idea past Laura & Jon who seem happy to go for it and give it a try.

feat(100): try to push one "fix" for our accessibility score

---

src/StockportWebapp/Views/healthystockport/Shared/SubItem-List.cshtml
src/StockportWebapp/Views/healthystockport/Topic/Index.cshtml

During sign off - it was requested that the Subitems ( Primary Items in Contentful ) would only display images if ALL Primary items had an image to display.
A lock, of sorts, to stop having a potentially different navigation items and funky layout.
This is a similar action to how Stockport Gov works with it's Topic.

fix(HS_TOPIC_NAVIGATION): display if ALL have img

---

src/StockportWebapp/ContentFactory/TopicFactory.cs

Add CallToAction in new ProcessedTopic model in new Factory.
I need to run a refactor card for Healthy Stockport > Topic as now the Events API call can go within the factory too. But, I may need to add this in to the constructor to ensure it's not left out. Although I don't "like" that massive constructor on the model, I can't see right now what way would be better. It previously didn't need to be in the constructor when it was simply model bound as is.

feat(CallToAction): + property to processed model

---

src/StockportWebapp/wwwroot/assets/javascript/stockportgov/viewMoreSlider.js

I pushed a bug into IE for the initial quick fix of the view more slider interrupting the Recite Me script which was blocking the use of the WebApp Accessibility tool.
The Accessibility tool works in IE now, but the View More Slider does not work as expected, as IE does not support the JavaScript function I used ( .includes ).  So, needed to switch the logic to include IE browser support, and use the ".search" string api, which returns the starting index of the substring found match in the string. If no match is found it returns a "-1".

fix(ViewMoreSlider): change .includes to .search

---

src/StockportWebapp/Views/stockportgov/Events/Detail.cshtml

"The way we display the time of event is inconsistent - change the display of the time on an event so that it is in 12 hours am/pm format on the events page" - [jira card](https://stockportbi.atlassian.net/browse/DIGITAL-8732) circa 2022

chore(events): change time to 12 hour from 24 hour

---

src/StockportWebapp/Views/stockportgov/Events/Detail.cshtml

The way i had the time formatted (10:00 AM) didn't match with the way it's shown before you click on the event (10:00am), so this is a change to fix that.

chore(events): make datetime format match homepage style

---

src/StockportWebapp/Controllers/EventsController.cs

revert the controller action that needs the view specified ( as it was before I changed it ) because the implied view does not exist.

fix(Events): specific view returned

---

src/StockportWebapp/Parsers/CarouselTagParser.cs

The carousel was not working when rendered through the Tag Parser, as I missed it off when I was updating the assets loading for require.js.
This simply adds the script tag from the partial view into the string in the Tag Parser

fix(Carousel): added script tag to Parser

---

src/StockportWebapp/Controllers/EventsController.cs
src/StockportWebapp/Views/Shared/ShareViaCalendar.cshtml
src/StockportWebapp/wwwroot/robots-healthystockport-live.txt
src/StockportWebapp/wwwroot/robots-stockportgov-live.txt

IAction Result cannot return null
the url https://www.stockport.gov.uk/events/add-to-calendar returns a 500 error because of it.
add the url to robots.txt file so it’s not indexed / crawlable
return Ok, not null… and NotFound if no “type” in the request

fix(Events): "add-to-calendar" url return type

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/nav-card-functionality.cy.js

I have written a test that checks the number of Navcards and then clicks on the first one to make sure it goes to a new location. The content in the Navcards is content managed so not sure if this test is all that useful and might get removed as we keep adding tests.

tests(navcard): amend cypress test

---

test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/alert-functionality.cy.js
test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/navcard-functionality.cy.js
test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/search-functionality.cy.js
test/UIAndBrowserTests/cypress/e2e/BrowserTests/Homepage/view-more-services-button-functionality.cy.js

-Added test to cover hover colour change for the search button on Cludo Search 
-Added test to cover keyboard only for the view more services button under the our services section

test(Webapp Browser): added additional tests for search and our services

---

src/StockportWebapp/Utils/CookiesHelper.cs

If the slug doesn't have a value, then the alert won't be registered in the cookies

fix(CookiesHelper): add check for null slugs

---

src/StockportWebapp/Views/stockportgov/Shared/GlobalAlert.cshtml

Added data-cy="global-alert-wrapper" to the GlobalAlert.cstml. Not sure this is the right place but need to try it, the UI snapshot tests and structure tests for alerts are failing due to the data-cy="global-alert-wrapper" no longer being there. Not sure when it was removed but the tests have worked previously.

refactor(Webapp): added data cy to global alert html

---

src/StockportWebapp/Views/stockportgov/Directory/DirectoryEntry.cshtml

- 'Facilities Available' title was hardcoded, so was always appearing even if with no filters highlighted.
- Add linq query to find all filters where 'Highlight' is true, reuse that for displaying them instead of previous two for loops.

chore(view): update highlightFilter logic

---

src/StockportWebapp/Views/stockportgov/Directory/DirectoryEntry.cshtml

- Change to content api means the filters list can no longer be null, only empty.
- Swap null check to .Any to handle this.

fix(directory-entry): only show filters section if highlight bool true

---

src/StockportWebapp/Views/stockportgov/Directory/DirectoryEntry.cshtml

- Nu html checker was showing an error when an img contains a srcset attribute without a sizes attribute. The Mozilla docs provide examples that only contatin a srcset attribute so I'm not sure how required it is.
- Not able to use the nu html checker to test locally so have just removed the size from the end of the srcset tag to see if that makes a difference for now.

chore(directory-entry): image tag for nu html error

---

src/StockportWebapp/Views/stockportgov/Shared/ArticleNavCardList.cshtml

If an article was the last item the padding bottom wasn't displaying properly.
The sidebarItems now only contains items that aren't the current item, so item.Last() should now work as intended.

chore(navcardList): remove current item for subItems
